name: build-release
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Extract Current Branch Name
        shell: bash
        # bash pattern expansion to grab the branch name without the slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "branch=${ref////-}" >> $GITHUB_OUTPUT
        id: ref

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Gradle Build
        run: ./gradlew check build

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FluxApi-artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/*.jar

      - name: Upload Binaries to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*.jar
          file_glob: true

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToCRMReleasesRepository
        env:
          CRMReleasesUsername: ${{ secrets.CRM_GITHUB_USER }}
          CRMReleasesPassword: ${{ secrets.CRM_GITHUB_PASS }}
